# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rUx57Dx9DdoG5ZrojWj7gxZ1b8-2F7uo
"""

print("CV 1")
cv1= {"Name": "Yabiş Ubeyliş", "Date of birth": "20.03.1990", "Job Title":"Senior Developer", "Graduated from":"Harvard University"}

for k, v in cv1.items():
  print(k, ' : ', v)

print("CV 2")
cv2 = {"Name":"Kureyşli Kayluş", "Date of birth": "10.02.1995", "Job Title":"Web Designer", "Graduated from":"Düzce University"}
for k, v in cv2.items():
  print(k, ' : ', v)

print("CV 3")
cv3 = {"Name":"Katrina Olga Natasha Swarovski", "Date of birth": "29.12.1993", "Job Title":"Graphic Designer", "Graduated from":"St.Petersburg University"}
for k, v in cv3.items():
  print(k, ' : ', v)

print("CV 4")
cv4 = {"Name":"Bum Bebi", "Date of birth":"22.07.1994", "Job Title":"2D & 3D Animator","Graduated from":"Hacettepe University"}
for k, v in cv4.items():
  print(k, ' : ', v)

print("CV 5")
cv5 = {"Name":"Du Tıs", "Date of birth":"19.07.1985", "Job Title":"Data Scientist", "Graduated from":"Peking University"}
for k, v in cv5.items():
  print(k, ' : ', v)